let nombre = "Cristina"
let apellido = "Cerro"
let estudiante = nombre +" "+ apellido
let estudianteMayus = estudiante.toUpperCase()
let estudianteMinus = estudiante.toLowerCase()
let numLetras = estudiante.length
let primLetra = nombre[0]
let ultLetra = apellido.charAt(apellido.length-1)
let no_space = estudiante.trim()
let incluyeNombre = estudiante.includes(nombre)